{ config, ... }:

{
  programs.foot = {
    enable = true;

    settings = {
      main.font = "Hack Nerd Font Mono:size=12";
      colors.alpha = 0.90;

      # Wallpaper-driven colors (Option B): this file is generated by `walltheme`.
      # It must exist at runtime; if missing, foot falls back to built-in defaults.
      main.include = "~/.config/foot/theme.ini";
    };
  };
}
